apiVersion: v1
kind: Service
metadata:
  name: fastapi-rollouts-cd-demo
  namespace: argo
spec:
  type: NodePort
  selector:
    app: fastapi-rollouts-cd-demo
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 32220
